'use strict';
const $ = id => document.getElementById(id);
const labels = {chapters:'章节编辑',location:'地点卡',item:'物品卡',rule:'规则设定卡'};
const state = {project:null,mode:'chapters',current:null,baseline:'',busy:false,history:[],historyIndex:0};
const clone = value => JSON.parse(JSON.stringify(value));
function node(tag, className, text) { const el=document.createElement(tag); if(className)el.className=className; if(text!==undefined)el.textContent=text; return el; }
function status(text) { $('status').textContent=text; }
function report(error) { $('error-text').textContent=error.message || String(error); $('error').hidden=false; status('操作未完成'); }
function clearError() { $('error').hidden=true; }
function snapshot() { return JSON.stringify(state.current); }
function dirty() { return Boolean(state.current && snapshot()!==state.baseline); }
function touch() { $('dirty-badge').textContent=dirty()?'● 未保存':state.current?'已保存':'未选择'; $('dirty-badge').classList.toggle('dirty',dirty()); $('save').disabled=state.busy || !state.current || !dirty(); }
function setBusy(value) { state.busy=value; $('app').classList.toggle('busy',value); $('app').setAttribute('aria-busy',String(value)); document.querySelectorAll('.app button,.app input,.app textarea').forEach(el=>el.disabled=value); if(!value)updateControls(); }
function updateControls() { if(state.busy){document.querySelectorAll('.app button,.app input,.app textarea').forEach(el=>el.disabled=true);return;} $('delete').disabled=!state.current || Boolean(state.current.isNew); $('save').disabled=!state.current || !dirty(); $('create').disabled=!state.project?.path; $('empty-create').disabled=!state.project?.path; $('export').disabled=!state.project?.path; $('import').disabled=!state.project?.path; const numbers=chapterNumbers(); const index=numbers.indexOf(state.current?.number); $('previous').disabled=state.mode!=='chapters'||index<=0; $('next').disabled=state.mode!=='chapters'||index<0||index>=numbers.length-1; $('undo').disabled=state.historyIndex<=0; $('redo').disabled=state.historyIndex>=state.history.length-1; }
async function run(action) { if(state.busy)return; setBusy(true); clearError(); try { await action(); } catch(error) { report(error); } finally { setBusy(false); touch(); } }
async function api(path, method='GET', data) { const headers={}; if(method!=='GET'){headers['Content-Type']='application/json';headers['X-Novel-Request']='1';if(path!=='/api/project')headers['X-Novel-Project']=state.project.path;} const response=await fetch(path,{method,headers,body:data===undefined?undefined:JSON.stringify(data),cache:'no-store'}); let result; try {result=await response.json();} catch {throw new Error('服务器响应格式无效，请检查本地服务。');} if(!response.ok) {const error=new Error((result.error||'请求失败')+(response.status===409?'。本地编辑已保留，请重新加载后核对修改。':''));error.status=response.status;throw error;}return result; }
async function loadProject() { const project=await api('/api/project'); state.project=project; $('project-path').value=project.path||''; $('project-summary').textContent=`${project.chapters.length} 章 · ${project.cards.length} 张设定卡`; for(const mode of Object.keys(labels))$('count-'+mode).textContent=mode==='chapters'?project.chapters.length:project.cards.filter(c=>c.type===mode).length; renderList(); }
function chapterNumbers() { return (state.project?.chapters||[]).map(c=>c.number).sort((a,b)=>a-b); }
function renderList() { const list=$('entries');list.replaceChildren(); const query=$('list-search').value.trim().toLocaleLowerCase();const chapters=state.mode==='chapters';const entries=chapters?[...(state.project?.chapters||[])].sort((a,b)=>a.number-b.number):(state.project?.cards||[]).filter(c=>c.type===state.mode);const filtered=entries.filter(c=>chapters?`第 ${c.number} 章`.includes(query):[c.name,...Object.values(c.fields)].join('\n').toLocaleLowerCase().includes(query));$('list-count').textContent=`${filtered.length}${query?' / '+entries.length:''} ${chapters?'章':'张'}`; for(const item of filtered){ const selected=state.current && (chapters?state.current.number===item.number:state.current.id===item.id);const button=node('button','entry'+(selected?' selected':''));button.setAttribute('aria-pressed',String(Boolean(selected)));button.append(node('span','entry-title',chapters?`第 ${item.number} 章`:item.name));button.append(node('span','entry-sub',chapters?'正文':(item.enabled?'已启用':'已停用')+' · '+(Object.values(item.fields).find(Boolean)||'暂无内容')));button.addEventListener('click',()=>run(async()=>{if(selected){$('app').classList.remove('list-open');return;}if(!await guard())return;await select(item);$('app').classList.remove('list-open');}));list.append(button);} if(!filtered.length)list.append(node('div','list-empty',query?'没有匹配的内容':chapters?'暂无章节':'暂无设定卡')); }
async function select(item) { const current=state.mode==='chapters'?{...await api('/api/chapters/'+item.number),isNew:false}:clone(item);state.current=current;state.baseline=snapshot();renderEditor();renderList(); }
function resetCurrent() { state.current=null;state.baseline='';renderEditor();renderList(); }
function renderEditor() { const current=state.current, chapters=state.mode==='chapters';$('empty').hidden=Boolean(current);$('chapter-editor').hidden=!current||!chapters;$('card-editor').hidden=!current||chapters;$('editor-title').textContent=current?(chapters?`第 ${current.number} 章`:current.name||'未命名'+labels[state.mode]):labels[state.mode];$('breadcrumb').textContent=chapters?'正文 / 章节编辑':'世界设定 / '+labels[state.mode];$('empty-title').textContent=chapters?'开始新的一章':'创建'+labels[state.mode];$('empty-create').textContent=chapters?'新建章节':'新建'+labels[state.mode];if(current&&chapters){$('chapter-text').value=current.text;state.history=[{text:current.text,start:0,end:0}];state.historyIndex=0;updateStats();}if(current&&!chapters){$('card-name').value=current.name;$('card-enabled').checked=current.enabled;$('card-fields').replaceChildren();const fields=state.project.card_types[state.mode][1];for(const [key,label] of Object.entries(fields)){const wrapper=node('label','field',label);const input=node('textarea');input.value=current.fields[key]||'';input.dataset.field=key;input.addEventListener('input',()=>{state.current.fields[key]=input.value;touch();});wrapper.append(input);$('card-fields').append(wrapper);}} touch();updateControls(); }
function updateStats() {const input=$('chapter-text');$('word-count').textContent=`${Array.from(input.value.replace(/\s/gu,'')).length.toLocaleString()} 字`;const before=input.value.slice(0,input.selectionStart);$('cursor-position').textContent=`第 ${before.split('\n').length} 行，第 ${Array.from(before.slice(before.lastIndexOf('\n')+1)).length+1} 列`;}
function recordHistory() {const input=$('chapter-text');const last=state.history[state.historyIndex];if(last?.text!==input.value){state.history.splice(state.historyIndex+1);state.history.push({text:input.value,start:input.selectionStart,end:input.selectionEnd});if(state.history.length>150)state.history.shift();state.historyIndex=state.history.length-1;}state.current.text=input.value;touch();updateStats();updateControls();}
function undo(direction) {if(state.busy||state.mode!=='chapters'||!state.current)return;const index=state.historyIndex+direction;if(index<0||index>=state.history.length)return;state.historyIndex=index;const entry=state.history[index],input=$('chapter-text');input.value=entry.text;input.setSelectionRange(entry.start,entry.end);state.current.text=entry.text;input.focus();touch();updateStats();updateControls();}
function dialog(title, build, actions) { return new Promise(resolve=>{const modal=$('dialog');$('dialog-title').textContent=title;$('dialog-body').replaceChildren();$('dialog-actions').replaceChildren();build($('dialog-body'));let settled=false;const finish=value=>{if(settled)return;settled=true;modal.close();resolve(value);};for(const action of actions){const button=node('button',action.style||'secondary',action.label);button.type='button';button.addEventListener('click',()=>{const value=action.value;if(action.validate&&!action.validate())return;finish(value);});$('dialog-actions').append(button);}modal.oncancel=event=>{event.preventDefault();finish('cancel');};$('dialog-form').onsubmit=event=>event.preventDefault();modal.showModal();}); }
async function confirmAction(title,message,label='确认') {return await dialog(title,body=>body.append(node('p','',message)),[{label:'取消',value:'cancel'},{label,value:'confirm',style:'primary'}])==='confirm';}
async function guard() {if(!dirty())return true;const choice=await dialog('保存当前修改？',body=>body.append(node('p','', '当前内容尚未保存。离开后，未保存的修改将丢失。')),[{label:'取消',value:'cancel'},{label:'放弃修改',value:'discard'},{label:'保存并继续',value:'save',style:'primary'}]);if(choice==='cancel')return false;if(choice==='save')await save();return true;}
async function save() {if(!state.current)return;const current=state.current;if(state.mode==='chapters'){await api(current.isNew?'/api/chapters':'/api/chapters/'+current.number,current.isNew?'POST':'PUT',current.isNew?{number:current.number,text:current.text}:{text:current.text,revision:current.revision});await loadProject();await select({number:current.number});}else{if(!current.name.trim())throw new Error('请填写卡片名称。');if(state.project.cards.some(card=>card.type===current.type&&card.id!==current.id&&card.name.trim().toLocaleLowerCase()===current.name.trim().toLocaleLowerCase()))throw new Error('此类型中已存在同名卡片。');const card=clone(current);delete card.isNew;await api('/api/cards','POST',{card,cards_revision:state.project.cards_revision});await loadProject();const saved=state.project.cards.find(c=>c.id===card.id);if(!saved)throw new Error('保存后未找到卡片，请重新加载项目。');await select(saved);}status('已保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})); }
async function create() {if(!state.project?.path)throw new Error('请先打开项目目录。');if(!await guard())return;if(state.mode==='chapters'){let number;const result=await dialog('新建章节',body=>{const label=node('label','dialog-field','章节编号');const input=node('input');input.id='new-number';input.type='number';input.min='1';input.step='1';input.value=String(Math.max(0,...chapterNumbers())+1);label.append(input);body.append(label,node('p','dialog-error'));},[{label:'取消',value:'cancel'},{label:'创建',value:'create',style:'primary',validate:()=>{number=Number($('new-number').value);const valid=Number.isSafeInteger(number)&&number>0&&!chapterNumbers().includes(number);if(!valid)$('dialog-body').querySelector('.dialog-error').textContent='请输入未使用的正整数章节编号。';return valid;}}]);if(result!=='create')return;state.current={number,text:'',isNew:true};}else{state.current={id:globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),type:state.mode,name:'',enabled:true,fields:Object.fromEntries(Object.keys(state.project.card_types[state.mode][1]).map(key=>[key,''])),isNew:true};}state.baseline='';renderEditor();renderList();$('app').classList.remove('list-open');status('新建内容尚未保存');requestAnimationFrame(()=>(state.mode==='chapters'?$('chapter-text'):$('card-name')).focus()); }
async function switchMode(mode) {if(mode===state.mode)return;if(!await guard())return;state.mode=mode;$('list-search').value='';$('list-title').textContent=labels[mode];$('list-search').placeholder=mode==='chapters'?'搜索章节':'搜索名称或内容';$('list-sort').textContent=mode==='chapters'?'章节顺序':'全部状态';$('card-actions').hidden=mode==='chapters';$('create').title=$('create').ariaLabel=mode==='chapters'?'新建章节':'新建'+labels[mode];document.querySelectorAll('[data-mode]').forEach(button=>{button.classList.toggle('active',button.dataset.mode===mode);button.setAttribute('aria-pressed',String(button.dataset.mode===mode));});resetCurrent();const first=mode==='chapters'?state.project?.chapters.slice().sort((a,b)=>a.number-b.number)[0]:state.project?.cards.find(c=>c.type===mode);if(first)await select(first); }
async function refresh() {if(!await guard())return;const old=state.current;await loadProject();const item=state.mode==='chapters'?state.project.chapters.find(c=>c.number===old?.number):state.project.cards.find(c=>c.id===old?.id);if(item)await select(item);else resetCurrent();status('项目已重新加载');}
async function remove() {const current=state.current;if(!current||current.isNew)return;const name=state.mode==='chapters'?`第 ${current.number} 章`:current.name;if(!await confirmAction('删除'+(state.mode==='chapters'?'章节':'卡片'),`确定删除“${name}”？此操作无法撤销${dirty()?'，未保存的修改也将丢失':''}。`,'删除'))return;await api(state.mode==='chapters'?'/api/chapters/'+current.number:'/api/cards/'+encodeURIComponent(current.id),'DELETE',state.mode==='chapters'?{revision:current.revision}:{cards_revision:state.project.cards_revision});await loadProject();resetCurrent();status('已删除 '+name); }
async function importCards() {if(!await guard())return;let payload,replace;const result=await dialog('导入设定卡',body=>{const label=node('label','dialog-field','JSON 文件');const input=node('input');input.type='file';input.id='import-file';input.accept='.json,application/json';label.append(input);body.append(label);for(const [value,text] of [['merge','合并：保留现有卡片'],['replace','替换：删除全部现有卡片后导入']]){const option=node('label','radio-option');const radio=node('input');radio.type='radio';radio.name='import-mode';radio.value=value;radio.checked=value==='merge';option.append(radio,document.createTextNode(' '+text));body.append(option);}body.append(node('p','dialog-error'));},[{label:'取消',value:'cancel'},{label:'继续',value:'import',style:'primary',validate:()=>{const file=$('import-file').files[0];if(!file){$('dialog-body').querySelector('.dialog-error').textContent='请选择 JSON 文件。';return false;}payload=file;replace=$('dialog-body').querySelector('input[name=import-mode]:checked').value==='replace';return true;}}]);if(result!=='import')return;let parsed;try{parsed=JSON.parse(await payload.text());}catch{throw new Error('JSON 格式错误，未导入任何内容。');}if(!parsed||parsed.version!==1||!Array.isArray(parsed.cards))throw new Error('文件需包含 version: 1 和 cards 数组。');if(!await confirmAction(replace?'确认替换全部设定卡':'确认合并设定卡',replace?`将删除当前项目全部 ${state.project.cards.length} 张卡片，替换为文件中的 ${parsed.cards.length} 张卡片。此操作无法撤销。`:`将导入 ${parsed.cards.length} 张卡片，保留已有卡片；名称或 ID 冲突将取消整个导入。`,replace?'替换全部':'合并导入'))return;await api('/api/cards/import','POST',{payload:parsed,replace,cards_revision:state.project.cards_revision});await loadProject();resetCurrent();status('设定卡已导入'); }
function findNext() {const input=$('chapter-text'),query=$('find-text').value;if(!query){$('find-result').textContent='请输入查找文本';return false;}let index=input.value.indexOf(query,input.selectionEnd);if(index<0)index=input.value.indexOf(query);if(index<0){$('find-result').textContent='未找到匹配项';return false;}input.focus();input.setSelectionRange(index,index+query.length);const count=input.value.split(query).length-1;$('find-result').textContent=`共 ${count} 处匹配`;updateStats();return true;}
function replaceText(all) {const input=$('chapter-text'),query=$('find-text').value,replacement=$('replace-text').value;if(!query){$('find-result').textContent='请输入查找文本';return;}if(all){const count=input.value.split(query).length-1;if(!count){$('find-result').textContent='未找到匹配项';return;}input.setRangeText(input.value.split(query).join(replacement),0,input.value.length,'start');recordHistory();$('find-result').textContent=`已替换 ${count} 处`;}else{if(input.value.slice(input.selectionStart,input.selectionEnd)!==query){findNext();return;}input.setRangeText(replacement,input.selectionStart,input.selectionEnd,'end');recordHistory();findNext();}}
$('navigation').addEventListener('click',event=>{const button=event.target.closest('[data-mode]');if(button)run(()=>switchMode(button.dataset.mode));});
$('list-search').addEventListener('input',renderList);
$('save').addEventListener('click',()=>run(save));$('create').addEventListener('click',()=>run(create));$('empty-create').addEventListener('click',()=>run(create));$('delete').addEventListener('click',()=>run(remove));$('refresh').addEventListener('click',()=>run(refresh));$('dismiss-error').addEventListener('click',clearError);
$('open-project').addEventListener('click',()=>run(async()=>{const path=$('project-path').value.trim();if(!path)throw new Error('请输入项目目录。');if(!await guard())return;await api('/api/project','POST',{path});await loadProject();resetCurrent();if(state.mode==='chapters'&&state.project.chapters.length)await select({number:chapterNumbers()[0]});status('项目已打开');}));
$('project-path').addEventListener('keydown',event=>{if(event.key==='Enter')$('open-project').click();});
$('card-name').addEventListener('input',()=>{state.current.name=$('card-name').value;$('editor-title').textContent=state.current.name||'未命名'+labels[state.mode];touch();});$('card-enabled').addEventListener('change',()=>{state.current.enabled=$('card-enabled').checked;touch();});
$('chapter-text').addEventListener('input',recordHistory);for(const event of ['click','keyup','select'])$('chapter-text').addEventListener(event,updateStats);
$('undo').addEventListener('click',()=>undo(-1));$('redo').addEventListener('click',()=>undo(1));
for(const [id,direction] of [['previous',-1],['next',1]])$(id).addEventListener('click',()=>run(async()=>{const numbers=chapterNumbers(),number=numbers[numbers.indexOf(state.current.number)+direction];if(number!==undefined&&await guard())await select({number});}));
$('toggle-find').addEventListener('click',()=>{$('find-panel').hidden=!$('find-panel').hidden;if(!$('find-panel').hidden)$('find-text').focus();});$('find-next').addEventListener('click',findNext);$('replace-one').addEventListener('click',()=>replaceText(false));$('replace-all').addEventListener('click',()=>replaceText(true));$('find-text').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();findNext();}});
$('toggle-list').addEventListener('click',()=>$('app').classList.toggle('list-open'));
$('import').addEventListener('click',()=>run(importCards));$('export').addEventListener('click',()=>run(async()=>{const response=await fetch('/api/cards/export',{cache:'no-store'});if(!response.ok){let data={};try{data=await response.json();}catch{}throw new Error(data.error||'导出失败');}const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download='setting_cards.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status('已导出磁盘中的设定卡');}));
document.addEventListener('keydown',event=>{if(!(event.ctrlKey||event.metaKey))return;const key=event.key.toLowerCase();if(key==='s'){event.preventDefault();if(!$('dialog').open)run(save);}if(key==='f'){event.preventDefault();if(!state.busy&&!$('dialog').open){$('app').classList.add('list-open');$('list-search').focus();$('list-search').select();}}if(event.target===$('chapter-text')&&(key==='z'||key==='y')){event.preventDefault();undo(key==='y'||event.shiftKey?1:-1);}});
window.addEventListener('beforeunload',event=>{if(dirty()){event.preventDefault();event.returnValue='';}});
run(async()=>{await loadProject();if(state.project.chapters.length)await select({number:chapterNumbers()[0]});else resetCurrent();status(state.project.path?'本地项目已就绪':'请打开项目目录');});
