'use strict';
const $=id=>document.getElementById(id),tabs=['Main Functions','Novel Architecture','Chapter Blueprint','Character State','Global Summary','章节编辑','设定卡库','Other Settings'],docKeys=['architecture','blueprint','character','summary'];
const S={tab:0,sub:0,project:null,config:null,configBase:'',configRevision:'',secretPaths:[],clearSecrets:[],copySecrets:[],llm:'',embedding:'',params:{},main:{text:'',base:'',number:'',revision:null},documents:{},chapter:null,card:null,cardType:'location',logs:[],task:null,busy:false,english:false};
const copy=x=>JSON.parse(JSON.stringify(x)),json=x=>JSON.stringify(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function status(m){$('status').textContent=m;}function error(e){$('error').hidden=false;$('error').querySelector('span').textContent=e.message||String(e);status('操作未完成；编辑内容已保留');}
function log(m){S.logs.push(String(m));if(S.logs.length>3000)S.logs.splice(0,100);if($('log')){$('log').value=S.logs.join('\n');$('log').scrollTop=$('log').scrollHeight;}}
async function api(path,method='GET',body){const headers={'X-Novel-Request':'1'};if(method!=='GET'){headers['Content-Type']='application/json';if(path!=='/api/project'&&S.project)headers['X-Novel-Project']=encodeURIComponent(S.project.path);}const r=await fetch(path,{method,headers,body:body===undefined?undefined:json(body),cache:'no-store'});let result;try{result=await r.json();}catch{throw Error('服务器响应无效，请检查服务。');}if(!r.ok)throw Error((result.error||'请求失败')+(r.status===409?'。请保留修改后重新加载最新版本。':''));return result;}
async function run(fn){if(S.busy)return;S.busy=true;$('error').hidden=true;document.body.classList.add('busy');try{await fn();}catch(e){error(e);}finally{S.busy=false;document.body.classList.remove('busy');}}
function bind(id,event,fn){const e=$(id);if(e)e.addEventListener(event,fn);}function button(id,text,cls=''){return `<button id="${id}" class="${cls}">${text}</button>`;}function opts(values,selected){return values.map(v=>`<option value="${esc(v)}" ${String(v)===String(selected)?'selected':''}>${esc(v)}</option>`).join('');}
function field(id,label,value='',type='text',attrs=''){return `<div class="field"><label for="${id}">${label}</label><div class="control"><input id="${id}" type="${type}" value="${esc(value)}" ${attrs}></div></div>`;}function textField(id,label,value=''){return `<div class="field"><label for="${id}">${label}</label><div class="control"><textarea id="${id}">${esc(value)}</textarea></div></div>`;}function selectField(id,label,values,value){return `<div class="field"><label for="${id}">${label}</label><div class="control"><select id="${id}">${opts(values,value)}</select></div></div>`;}function count(t){return [...t.replace(/\s/gu,'')].length;}
function modal(title,build,actions=[['cancel','取消'],['ok','确定']]){return new Promise(resolve=>{const d=$('modal');$('modal-title').textContent=title;$('modal-body').replaceChildren();$('modal-actions').replaceChildren();build($('modal-body'));let done=false;const finish=v=>{if(done)return;done=true;d.close();resolve(v);};for(const[value,text,cls]of actions){const b=el('button',text,cls||'');b.type='button';b.onclick=()=>finish(value);$('modal-actions').append(b);}d.oncancel=e=>{e.preventDefault();finish('cancel');};$('modal-form').onsubmit=e=>e.preventDefault();d.showModal();});}
async function confirm(title,message){return await modal(title,b=>b.append(el('p',message)))==='ok';}async function ask(title,value='',label='名称'){let input;const a=await modal(title,b=>{const l=el('label',label);input=el('input');input.value=value;l.append(input);b.append(l);});return a==='ok'?input.value:null;}
async function guard(label,dirty,save){if(!dirty)return true;const a=await modal('未保存修改',b=>b.append(el('p',`${label}尚未保存，是否保存后继续？`)),[['cancel','取消'],['discard','放弃修改'],['save','保存并继续']]);if(a==='cancel')return false;if(a==='save')await save();return true;}
function configDirty(){return Boolean(S.config&&json(S.config)!==S.configBase||S.clearSecrets.length);}function entityDirty(v){return v&&v.base!==v.text;}function cardDirty(){return S.card&&json(S.card.value)!==S.card.base;}function visibleDirty(){if(S.tab===0)return entityDirty(S.main);if(S.tab<=4)return entityDirty(S.documents[docKeys[S.tab-1]]);if(S.tab===5)return entityDirty(S.chapter);if(S.tab===6)return cardDirty();return false;}async function guardVisible(){return guard('当前编辑内容',visibleDirty(),saveVisible);}async function saveVisible(){if(S.tab===0)return saveMain();if(S.tab<=4)return saveDoc(docKeys[S.tab-1]);if(S.tab===5)return saveChapter();if(S.tab===6)return saveCard();}
async function guardAll(){if(!await guardVisible())return false;return guard('模型及小说参数配置',configDirty(),saveConfig);}function dirtyMark(){if($('dirty'))$('dirty').textContent=visibleDirty()?'● 未保存':'已保存';if($('cfg-dirty'))$('cfg-dirty').textContent=configDirty()?'配置有未保存修改':'';}
async function loadProject(){S.project=await api('/api/project');status(`当前项目：${S.project.path}`);}async function loadConfig(){const r=await api('/api/config');S.config=r.config;S.configBase=json(r.config);S.configRevision=r.revision;S.secretPaths=r.secret_paths||[];S.clearSecrets=[];S.copySecrets=[];S.llm=r.config.last_llm_config_name||Object.keys(r.config.llm_configs||{})[0]||'';S.embedding=r.config.last_embedding_interface_format||Object.keys(r.config.embedding_configs||{})[0]||'';S.params=copy(r.config.other_params||{});S.params.filepath=S.project.path;}
async function saveConfig(){S.config.other_params={...S.params,filepath:S.project.path};S.config.last_llm_config_name=S.llm;S.config.last_embedding_interface_format=S.embedding;const r=await api('/api/config','PUT',{config:S.config,revision:S.configRevision,clear_secret_paths:S.clearSecrets,copy_from:S.copySecrets});S.config=r.config;S.configBase=json(r.config);S.configRevision=r.revision;S.secretPaths=r.secret_paths||[];S.clearSecrets=[];S.copySecrets=[];status('配置已保存（密码保持脱敏）');dirtyMark();}
async function switchProject(path){if(!path.trim())throw Error('请填写小说保存目录');if(taskActive())throw Error('请等待当前任务结束再切换项目');if(!await guardAll())return;await api('/api/project','POST',{path});await loadProject();await loadConfig();S.documents={};S.chapter=null;S.card=null;S.main={text:'',base:'',number:'',revision:null};render();}
async function browse(){let input,path=S.project.path;const a=await modal('选择服务器本机小说目录',body=>{input=el('input');input.value=path;const go=el('button','打开目录'),up=el('button','上级目录'),list=el('div',undefined,'list'),hint=el('p','选择目录后点击确定；也可输入新目录路径。');body.append(input,go,up,list,hint);async function show(p){try{const r=await api('/api/folders?path='+encodeURIComponent(p));path=r.path;input.value=path;list.replaceChildren();for(const name of r.folders){const b=el('button',name);b.type='button';b.onclick=()=>show(path.replace(/[\\/]$/,'')+'/'+name);list.append(b);}}catch(e){hint.textContent=e.message;}}go.type=up.type='button';go.onclick=()=>show(input.value);up.onclick=()=>show(input.value.replace(/[\\/][^\\/]+[\\/]?$/,''));show(path);},[['cancel','取消'],['ok','选择此目录']]);if(a==='ok')await switchProject(input.value);}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',+b.dataset.tab===S.tab));if(S.tab===0)renderMain();else if(S.tab<=4)renderDoc();else if(S.tab===5)renderChapters();else if(S.tab===6)renderCards();else renderOther();dirtyMark();}
