'use strict';
function taskActive(){return S.task&&['queued','pending','running'].includes(S.task.status);}
async function startTask(action,extra={},skipConfirm=false){if(taskActive())throw Error('已有任务运行，请等待完成');const p={...S.params,...extra,english_mode:S.english,llm_config_name:S.llm,embedding_config_name:S.embedding};if(['architecture','blueprint','draft','build_prompt','finalize','batch'].includes(action)){for(const k of ['word_number','chapter_num'])if(!Number.isInteger(Number(p[k]))||Number(p[k])<1)throw Error('每章字数和章节号必须为正整数');if(['architecture','blueprint'].includes(action)&&Number(p.num_chapters)<1)throw Error('章节数必须大于零');}if(action==='batch'){let start,end,enrich,min;const a=await modal('批量生成章节',b=>{start=el('input');start.type='number';start.value=p.chapter_num||1;end=el('input');end.type='number';end.value=Number(start.value)+4;enrich=el('input');enrich.type='checkbox';enrich.checked=true;min=el('input');min.type='number';min.value=p.word_number||3000;const l=el('label','自动扩写');l.append(enrich);b.append(el('label','开始章节'),start,el('label','结束章节'),end,l,el('label','最低字数'),min);});if(a!=='ok')return;p.start_chapter=Number(start.value);p.end_chapter=Number(end.value);p.auto_enrich=enrich.checked;p.min_word_number=Number(min.value);if(p.start_chapter<1||p.end_chapter<p.start_chapter)throw Error('批量章节范围不合法');}
if(action==='finalize'){if(!S.main.text.trim())throw Error('请先加载或填写本章正文');const n=String(p.chapter_num);if(S.main.number&&S.main.number!==n)throw Error('编辑正文属于其他章节，请加载当前章节后定稿');if(!S.main.revision&&S.project.chapters.some(c=>String(c.number)===n))throw Error('当前章节已存在，请先加载正文以获得文件版本后再定稿');p.chapter_text=S.main.text;p.chapter_revision=S.main.revision||'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';let enrich;const a=await modal('定稿章节',b=>{b.append(el('p','将保存正文并更新角色状态、前文摘要与向量库。'));const l=el('label','字数不足时扩写');enrich=el('input');enrich.type='checkbox';l.append(enrich);b.append(l);});if(a!=='ok')return;p.should_enrich=enrich.checked;}
if(action==='clear_vectorstore'){if(!await confirm('清空向量库','确认删除当前小说的向量库？此操作不可撤销。'))return;p.confirm=true;}else if(!skipConfirm&&['architecture','blueprint','draft','batch'].includes(action)){if(!await guardVisible())return;if(!await confirm('确认生成',`${action==='architecture'?'小说架构':action==='blueprint'?'章节蓝图':action==='batch'?'批量章节':'章节草稿'}将调用所选模型，并可能覆盖对应文件，确定继续？`))return;}
await saveConfig();const r=await api('/api/tasks','POST',{action,params:p});S.task=r.task;S.taskAction=action;S.taskLogCount=0;S.taskProject=S.project.path;S.taskMainSnapshot=S.main.text;log('任务已提交：'+action);updateTaskStatus();pollTask();}
function updateTaskStatus(){const t=S.task;$('task-status').textContent=t?`${S.taskAction||t.action||'任务'} · ${t.status}`:'';document.querySelectorAll('[id^="step-"],#prompt-build,#test-llm,#test-embedding,#task-consistency,#task-knowledge,#task-clear').forEach(b=>b.disabled=Boolean(taskActive()));}
async function pollTask(){const id=S.task?.id;if(!id)return;try{const r=await api('/api/tasks/'+encodeURIComponent(id));if(S.task?.id!==id)return;S.task=r.task;const logs=S.task.logs||[];for(const m of logs.slice(S.taskLogCount))log(typeof m==='string'?m:json(m));S.taskLogCount=logs.length;updateTaskStatus();if(taskActive()){setTimeout(pollTask,900);return;}if(S.task.status==='failed'){log('任务失败：'+(S.task.error||'未知错误'));error(Error(S.task.error||'任务失败'));return;}log('任务完成');await taskCompleted(S.taskAction,S.task.result||{});}catch(e){error(e);if(taskActive())setTimeout(pollTask,2500);}}
async function taskCompleted(action,result){if(S.taskProject!==S.project.path)return;if(result.text!==undefined){if(action==='build_prompt'){await run(async()=>{let text;const a=await modal('编辑章节提示词',b=>{text=el('textarea');text.value=result.text;b.append(text);},[['cancel','关闭'],['download','导出提示词'],['generate','使用此提示词生成草稿']]);if(a==='download')download('chapter_prompt.txt',text.value,'text/plain');if(a==='generate')await startTask('draft',{custom_prompt_text:text.value},false);});}else if(['draft','finalize'].includes(action)){if(S.main.text===S.taskMainSnapshot){S.main.text=result.text;S.main.base=result.text;S.main.number=String(S.params.chapter_num);try{const r=await api('/api/chapters/'+S.main.number);S.main.revision=r.revision;S.main.base=r.text;}catch{S.main.revision=null;S.main.base='';}if(S.tab===0)renderMain();}else log('生成内容已写入文件；编辑区存在后续修改，未覆盖编辑区。请手动加载。');}else if(['consistency','test_llm','test_embedding','plot_arcs'].includes(action))log(result.text);}
await loadProject();if(action==='architecture'&&!entityDirty(S.documents.architecture))await fetchDoc('architecture');if(action==='blueprint'&&!entityDirty(S.documents.blueprint))await fetchDoc('blueprint');if(S.tab>0&&S.tab<=4&&!visibleDirty())renderDoc();updateTaskStatus();}
async function importKnowledge(){let file,path,text;const a=await modal('导入知识库',b=>{file=el('input');file.type='file';file.accept='.txt,.md';path=el('input');path.placeholder='或输入服务器本机文件路径';text=el('textarea');text.placeholder='或粘贴知识文本';b.append(el('label','UTF-8 文本文件'),file,path,text);});if(a!=='ok')return;let p={};if(file.files.length)p.text=await file.files[0].text();else if(text.value.trim())p.text=text.value;else if(path.value.trim())p.file_path=path.value.trim();else throw Error('请选择文件、输入路径或粘贴文本');await startTask('knowledge_import',p,true);}
async function switchTab(i){if(i===S.tab)return;if(!await guardVisible())return;if(i>0&&i<=4&&!S.documents[docKeys[i-1]])await fetchDoc(docKeys[i-1]);S.tab=i;render();updateTaskStatus();}
for(const[t,i]of tabs.map((t,i)=>[t,i])){const b=el('button',t);b.dataset.tab=i;b.onclick=()=>run(()=>switchTab(i));$('tabs').append(b);}
bind('dismiss-error','click',()=>$('error').hidden=true);bind('language','click',()=>{S.english=!S.english;$('language').textContent=S.english?'to Chinese mode':'to English mode';status(S.english?'已切换英文生成提示词':'已切换中文生成提示词');});
document.addEventListener('keydown',e=>{if($('modal').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();run(()=>S.tab===7?saveConfig():saveVisible());}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'&&S.tab===5){e.preventDefault();$('find').focus();}if((e.ctrlKey||e.metaKey)&&S.tab===5&&e.target.id==='ch-text'&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();historyMove(e.key.toLowerCase()==='y'||e.shiftKey?1:-1);}});
window.addEventListener('beforeunload',e=>{if(visibleDirty()||configDirty()||entityDirty(S.main)||Object.values(S.documents).some(entityDirty)||entityDirty(S.chapter)||cardDirty()){e.preventDefault();e.returnValue='';}});
run(async()=>{await loadProject();await loadConfig();render();updateTaskStatus();}).catch(error);
